# This is a basic workflow to help you get started with Actions

       name: CI
       on:
         pull_request:
            branches: master
         workflow_dispatch:

       # A workflow run is made up of one or more jobs that can run sequentially or in parallel
       jobs:
         # This workflow contains a single job called "build"
         build:
           # The type of runner that the job will run on
           runs-on: macos-latest

           # Steps represent a sequence of tasks that will be executed as part of the job
           steps:
             # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
             - uses: actions/checkout@v2

             - run: |
                 pwd
                 swift package init --type library
                 xcodebuild clean
                 xcodebuild test -workspace CoffeeQuest.xcworkspace -scheme CoffeeQuest CODE_SIGN_ENTITLEMENTS= DEVELOPMENT_TEAM= CODE_SIGNING_ALLOWED=NO
